# Generated by Django 5.1.1 on 2024-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_question_subject_answer_quiz_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='classroom/covers'),
        ),
    ]
