# Generated by Django 5.1.1 on 2024-10-25 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio', models.CharField(max_length=200, verbose_name='Conquista:')),
                ('nivel_desafio', models.IntegerField(default=1)),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('categoria', models.CharField(blank=True, choices=[('Comum', 'Comum'), ('Incomum', 'Incomum'), ('Raro', 'Raro'), ('Épico', 'Épico'), ('Lendário', 'Lendário'), ('Mítico', 'Mítico')], max_length=11, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Insígnia:')),
                ('insignia', models.ImageField(blank=True, null=True, upload_to='insignia/imagens/')),
                ('insignia_descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição:')),
                ('insignia_descricao2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição_2:')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cont_add',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cont_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='contador1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='contador2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='contador3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='contador4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='contador5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='contador6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_1',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_1'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_10',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_10'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_11',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_11'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_12',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_12'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_13',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_13'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_14',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_14'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_15',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_15'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_16',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_16'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_17',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_17'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_18',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_18'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_19',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_19'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_2',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_2'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_20',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_20'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_21',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_21'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_22',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_22'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_23',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_23'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_24',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_24'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_25',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_25'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_26',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_26'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_27',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_27'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_28',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_28'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_29',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_29'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_3',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_3'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_30',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_30'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_31',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_31'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_32',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_32'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_33',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_33'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_34',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_34'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_35',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_35'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_36',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_36'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_4',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_4'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_5',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_5'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_6',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_6'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_7',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_7'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_8',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_8'),
        ),
        migrations.AddField(
            model_name='user',
            name='desafio_concluida_9',
            field=models.BooleanField(default=False, verbose_name='desafio_concluida_9'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_1',
            field=models.BooleanField(default=True, verbose_name='insignia_1'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_2',
            field=models.BooleanField(default=False, verbose_name='insignia_2'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_3',
            field=models.BooleanField(default=False, verbose_name='insignia_3'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_4',
            field=models.BooleanField(default=False, verbose_name='insignia_4'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_5',
            field=models.BooleanField(default=False, verbose_name='insignia_5'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_6',
            field=models.BooleanField(default=False, verbose_name='insignia_6'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_7',
            field=models.BooleanField(default=False, verbose_name='insignia_7'),
        ),
        migrations.AddField(
            model_name='user',
            name='insignia_8',
            field=models.BooleanField(default=False, verbose_name='insignia_8'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_desafio_concluidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome de usuário'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='primary')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/imagens/')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('avatar_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Tarefa:')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição:')),
                ('start_date', models.DateTimeField(verbose_name='Data de inicio:')),
                ('end_date', models.DateTimeField(verbose_name='Data de Termino:')),
                ('list_student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='list_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Alternativas')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.BooleanField(default=True, verbose_name='Status - <small>Opção define se os alunos vão poder visualizar esta avaliação ou não.</small>')),
                ('matter', models.CharField(default=None, max_length=255, verbose_name='Matéria')),
                ('subject_matter', models.CharField(default=None, max_length=255, verbose_name='Assunto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classroom.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.quiz'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='correct')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classroom.answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='classroom.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='classroom.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='classroom.subject'),
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('correct_answers', models.IntegerField(default='0')),
                ('incorrect_answers', models.IntegerField(default='0')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(through='classroom.TakenQuiz', to='classroom.quiz'),
        ),
    ]
