# Generated by Django 5.1.1 on 2024-11-25 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status - Opção define se os alunos vão poder visualizar esta avaliação ou não.'),
        ),
    ]
